galaxy_info:
  author: nekwebdev
  description: create git user and configure repositories
  company: tahiti-dev

  license: GPL-3.0-only

  min_ansible_version: 2.1

  platforms:
    - name: EL
      versions:
        - 8

  galaxy_tags: []

dependencies: []
